export const data = [
  {
    id: 1,
    name: 'Мужские Кроссовки Nike Blazer Mid Suede',
    price: 2999,
    imageUrl: '/assets/img/sneakers/1.jpg',
  },
  {
    id: 2,
    name: 'Мужские Кроссовки Nike Air Max 270',
    price: 1299,
    imageUrl: '/assets/img/sneakers/2.jpg',
  },
  {
    id: 3,
    name: 'Мужские Кроссовки Nike Blazer Mid Suede',
    price: 1499,
    imageUrl: '/assets/img/sneakers/3.jpg',
  },
  {
    id: 4,
    name: 'Кроссовки Puma X Aka Boku Future Rider',
    price: 1999,
    imageUrl: '/assets/img/sneakers/4.jpg',
  },
  {
    id: 5,
    name: 'Мужские Кроссовки Under Armour Curry 8',
    price: 1199,
    imageUrl: '/assets/img/sneakers/5.jpg',
  },
  {
    id: 6,
    name: 'Мужские Кроссовки Nike Kyrie 7',
    price: 1299,
    imageUrl: '/assets/img/sneakers/6.jpg',
  },
  {
    id: 7,
    name: 'Мужские Кроссовки Jordan Air Jordan 11',
    price: 1799,
    imageUrl: '/assets/img/sneakers/7.jpg',
  },
  {
    id: 8,
    name: 'Мужские Кроссовки Nike LeBron XVIII',
    price: 1499,
    imageUrl: '/assets/img/sneakers/8.jpg',
  },
  {
    id: 9,
    name: 'Мужские Кроссовки Nike Lebron XVIII Low',
    price: 1999,
    imageUrl: '/assets/img/sneakers/9.jpg',
  },
  {
    id: 10,
    name: 'Мужские Кроссовки Nike Blazer Mid Suede',
    price: 899,
    imageUrl: '/assets/img/sneakers/10.jpg',
  },
  {
    id: 11,
    name: 'Кроссовки Puma X Aka Boku Future Rider',
    price: 899,
    imageUrl: '/assets/img/sneakers/11.jpg',
  },
  {
    id: 12,
    name: 'Мужские Кроссовки Nike Kyrie Flytrap IV',
    price: 1299,
    imageUrl: '/assets/img/sneakers/12.jpg',
  },
  {
    id: 13,
    name: 'Женские Кроссовки Puma Electrify Nitro 2',
    price: 959,
    imageUrl: '/assets/img/sneakers/women1.svg',
  },
  {
    id: 14,
    name: 'Женские  Кроссовки Puma Easy Rider Vintage',
    price: 1299,
    imageUrl: '/assets/img/sneakers/women2.svg',
  },
  {
    id: 16,
    name: 'Женские Кроссовки Puma Explore Nitro Gtx',
    price: 1799,
    imageUrl: '/assets/img/sneakers/women3.svg',
  },
  {
    id: 17,
    name: 'Женские Кроссовки Puma Bmw Mms Roma Via',
    price: 1050,
    imageUrl: '/assets/img/sneakers/women4.svg',
  },
  {
    id: 18,
    name: 'Женские Кроссовки Puma Extend Lite Trail',
    price: 1550,
    imageUrl: '/assets/img/sneakers/women5.svg',
  },
  {
    id: 19,
    name: 'Женские Кроссовки Puma Speedfusion',
    price: 1799,
    imageUrl: '/assets/img/sneakers/women6.svg',
  },
];
